# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  create_infrastructure:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: aws/aws-cli
        aws_auth:
          aws_access_key_id: AKIATJZWQNBXWY7AHENF
          aws_secret_access_key: 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
          

    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Ensure backend infa exist"
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  my-workflow:
    jobs:
      - create_infrastructure
