version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  configure_role_arn:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile_name: default
      - aws-cli/role_arn_setup:
          profile_name: new-profile
          role_arn: arn:aws:iam::227210717295:user/ansiblecirclci
          source_profile: default
      - run: >-
          aws sts assume-role --role_arn
          "arn:aws:iam::227210717295:user/ansiblecirclci" --role_session_name
          AWSCLI-Session
workflows:
  aws-cli:
    jobs:
      - configure_role_arn
